name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up multiple JDKs
        id: setup-jdks
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: |
            21
            11

      - name: Some java work that requires JAVA 21
        env:
          JAVA_HOME: ${{ steps.setup-jdks.outputs.JAVA_HOME_21_x64 }}
        run: |
          echo "Using Java version:"
          java -version

      - name: Some java work that requires JAVA 11
        env:
          JAVA_HOME: ${{ steps.setup-jdks.outputs.JAVA_HOME_11_x64 }}
        run: |
          echo "Using Java version:"
          java -version
