name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up multiple JDKs
        id: setup-jdks
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: |
            21
            11

      - name: Print all outputs from setup-jdks
        run: echo "${{ toJSON(steps.setup-jdks.outputs) }}"

      - name: Set JAVA_HOME for Java 21
        run: echo "JAVA_HOME=${{ steps.setup-jdks.outputs.JAVA_HOME_21_x64 }}" >> $GITHUB_ENV

      - name: Some java work that requires JAVA 21
        run: |
          echo "Using Java version:"
          java -version

      - name: Set JAVA_HOME for Java 11
        run: echo "JAVA_HOME=${{ steps.setup-jdks.outputs.JAVA_HOME_11_x64 }}" >> $GITHUB_ENV

      - name: Some java work that requires JAVA 11
        run: |
          echo "Using Java version:"
          java -version
